### PR TITLE
fixed overflow on main window

### PR DESCRIPTION
**Pull request by micheleriva**
Hi!
I removed the annoying overflow bars of the main browser window.

Before:
schermata 2018-09-26 alle 11 54 04

After:
schermata 2018-09-26 alle 11 54 24

### CODE REVIEW

**Comment by joshwnj** [comment]
Nice, thanks! 

Btw, what OS are you on?

**Comment by joshwnj** [comment]
published to npm @1.2.1

**Comment by micheleriva** [comment]
I'm on OSX Sierra (macOS 10.12.6) 😄 

Great project! I'd love to contribute more with some new features 😃

**Comment by joshwnj** [comment]
cheers! new features welcome :)

**Pull request merged**
